<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)\GeneratedFiles</CompilerGeneratedFilesOutputPath>
    <StartupObject>OfiConvert.App</StartupObject>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <SignAssembly>false</SignAssembly>
    <Copyright>Ricky Angel Jimenez Bueno</Copyright>
    <Description>Convertidor de archivos Office a PDF</Description>
    <Version>1.0.0</Version>
    <AssemblyTitle>OfiConvert</AssemblyTitle>
    <Product>OfiConvert</Product>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\app.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="WPF-UI" Version="4.1.0" />
  </ItemGroup>

</Project>
